namespace Services.Models
{
    public enum SortOrder
    {
        Undefined = 0,
        Name = 1,
        Team = 2,
        Opponents = 3,
        Runs = 4,
        Totals = 4,
        Wickets = 5,
        Balls = 6,
        Season = 7,
        Played = 8,
        Wins = 9,
        lost = 10,
        Tied = 11,
        Drawn = 12,
        Byes = 13,
        LegByes = 14,
        Wides = 15,
        NoBalls = 16,
        MatchStartDate = 17,
        VictoryMargin = 18,
        SeriesDate = 19,
        Ground = 20,
        Host = 21,
        MatchStartYear = 22,
        Penalties = 23,
        Extras = 24,
        Percentage = 25,
        Dismissals = 26,
        Caught = 27,
        Stumpings = 28,
        cwk = 29,
        cf = 30,
        BestDismissals = 31,
        Innings = 32,
        Fours = 33,
        Sixes = 34,
        InningsNumber = 35,
        Bat1 = 36,
        Bat2 = 37,
        Minutes = 38,
        NotOuts = 39,
        hs = 40,
        avg = 41,
        fifties = 42,
        hundreds = 43,
        ducks = 44,
        bbi = 45,
        bbm = 46,
        maidens = 47,
        dots = 48,
        tenfor = 49,
        fivefor = 50,
        rpo = 51,
        strikerate = 52,
        ballsperover = 53,
        battingimpact = 54,
    }
    
    public enum SortDirection
    {
        Asc = 0,
        Desc
    }

}